name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pick an installed Xcode on the runner (latest 16.x)
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.x'

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # If you used Mint in your local Run Script phases
      - name: Tooling (Mint + format/lint)
        run: |
          brew install mint
          mint install realm/SwiftLint
          mint install nicklockwood/SwiftFormat

      - name: Build & Test (Debug)
        run: |
          set -e
          xcodebuild \
            -scheme "Chatty" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            clean build test \
            CODE_SIGNING_ALLOWED=NO

